name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Black formatter
        uses: psf/black@stable

      - name: Install docker-compose
        run: pip install docker-compose

      - name: Run linter
        run: docker-compose run app sh -c "flake8"
