name: Tests
on: [push, pull_request]
jobs:
  lint:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install docker-compose
        run: pip install docker-compose

      - name: Create environment
        run: docker-compose up db -d

      - name: Run tests
        run: docker-compose run app sh -c "python manage.py test"
